### ISSUE TITLE
CircleCI Partner Review

### ISSUE THREAD

**Issue by EricRibeiro** [Appdome/appdome-orb#4]
Hello AppDome team 👋

I am from the @circleci Community and Partner Engineering team, here to help with a review for the CircleCI orb partnership. I have a few action items below for you:

## Changes:

Please make the following changes:

### The orb lacks tests:

I don't see any tests running for the orb. The `command-tests` job only does a [checkout](https://app.circleci.com/pipelines/github/Appdome/appdome-orb/100/workflows/82b3a9b9-8602-4246-811f-75be0cbc1e13/jobs/742?invite=true#step-101-70). I see, however, a commented line in [test-deploy.yml](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/.circleci/test-deploy.yml#L21) that possibly should be uncommented (see below).

```yaml
jobs:
  test-android-private-sign: appdome-orb/appdome_runner
  test-appdome-api-enviorment: appdome-orb/test_appdome
  # Create a job to test the commands of your orbs.
  # You may want to add additional validation steps to ensure the commands are working as expected.
  command-tests:
    docker:
      - image: cimg/base:current
    steps:
      - checkout
      # Run your orb's commands to validate them.
      #- appdome-orb/appdome_runner
```

In the same way, `test-appdome-api-enviorment` only installs the repository requirements. Unless this is what you meant to test, something needs to be added. Please include tests for all jobs shipped with the orb to ensure they work.

### Change parameters with sensible information from `string` to `env_var_name`

Parameters like [keystore-password](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/commands/appdome_android_auto_signing.yml#L18) and [keystore-key-password](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/commands/appdome_android_auto_signing.yml#L26) are better of as [env_var_name](https://circleci.com/docs/reusing-config/#environment-variable-name) instead of [string](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/commands/appdome_android_auto_signing.yml#L19). This will force users to put them into safer places, like [Contexts](https://circleci.com/docs/contexts/). 

Notice, however, that with the `env_var_name` type, you cannot use parameters as you are doing [here](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/scripts/appdome_android_auto_sign.sh#L11). You will get a parameter name, not the value itself; therefore, you must expand the parameter:

```diff
- --keystore_pass "${KEYSTORE_PASS}" --key_pass "${KEYSTORE_KEY_PASS}"
+ --keystore_pass "${!KEYSTORE_PASS}" --key_pass "${!KEYSTORE_KEY_PASS}"
```

Or, if you want POSIX compliance:

```bash
KEYSTORE_PASS="$(eval printf '%s' "$KEYSTORE_PASS")"
KEYSTORE_KEY_PASS="$(eval printf '%s' "$KEYSTORE_KEY_PASS")"
--keystore_pass "${KEYSTORE_PASS}" --key_pass "${KEYSTORE_KEY_PASS}"
```

`APPDOME_API_KEY` should also be made a parameter in all commands/jobs that require it, and as the above, it must be of the `env_var_name` type. It's better to make its need explicit.

### Improve the `sign-overrides` description

Is it possible to describe [this](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/commands/appdome_android_auto_signing.yml#L37) parameter better? I can't easily find what it is supposed to be or do.

### Change the executor description and image

The executor description was left to the [default](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/executors/default.yml#L2). Please change it to match your needs. Additionally, it looks like `cimg/python` suits you better than `cimg/node`. Consider changing the default to the former.

### Remove `test_appdome.yml`

Unless you want to provide them for your users, test jobs should be defined and used inside `test-deploy.yml`. Having them as another "normal" job can lead to confusion and misuse. Additionally, this job only installs dependencies from `requirements.txt`; it isn't testing any orb-related functionality. 

### Remove the default executor if you want to enforce one

In `appdome_runner.yml`, the executor is hard coded to `cimg/python:3.9.16`. If this image and version are absolutely required, and you do not want users to stray from them, the [default executor](https://github.com/Appdome/appdome-orb/tree/5231879c36c2ee2eef654fe369698949931fdcc4/src/executors) is not needed and should be deleted. Otherwise, create a `version` parameter in the job and parameterize the executor:

```yaml
...
version:
    type: string
    default: '3.9.16'
    description: >
        Pick a specific cimg/python image version tag: https://hub.docker.com/r/cimg/python
...
executor:
    name: default
    tag: << parameters.version >>
...
```

### Fix typo in `appdome_runner.yml`

There is a small typo in [line 76](https://github.com/Appdome/appdome-orb/blob/5231879c36c2ee2eef654fe369698949931fdcc4/src/jobs/appdome_runner.yml#L76):

```diff
- name: Install requirments
+ name: Install requirements
```

## Final Thoughts

After addressing the issues above, please provide us with a successful run link. If you have any questions, please post them here; I'll be happy to help! I still need to review the script files. I will do that after I receive the aforementioned link.

Thank you 🙇
